### ISSUE TITLE
sudo make install does not work!

### ISSUE THREAD

**Issue by djarecka** [igfuw/drops.py#44]
my OSX:
make: *** No rule to make target `install'.  Stop.

**Comment by slayoo** [comment]
Just tested with igfuw/master and it seems to work (on Linux, but shouldn't make any difference).
This error message pops up if CMake was not run at all (or was run in another directory).

S.

**Comment by djarecka** [comment]
it really does not work (in my OSX) from build directory (this is in README!)
but I've just discovered that it works from drops.py and the build directory is empty...

**Comment by djarecka** [comment]
I've found in my diary that it used to be:
cd drops.py
cmake .
sudo make install
